import Layout from '../components/layout/layout';
import Image from 'next/image';

export default function Home() {
  return (
    <Layout pageTitle='Home Page'>
      <Image src='/nextjs.png' width={500} height={320} />
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <Image src='/next.png' width={500} height={320} />
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore perspiciatis quis labore corporis quasi suscipit quibusdam distinctio tempore magnam veritatis? Nemo, deserunt quaerat. Aliquam eos rerum fugit, excepturi tempora explicabo.</p>
      <Image src='/nextjs-analytics.png' width={500} height={320} />
    </Layout>
  )
}
